spring:
  application:
    name: eureka-center
  security:
    user:
      name: admin
      password: 149360

server:
  port: 8761
  servlet:
    context-path: /${spring.application.name}

info:
  groupId: @project.groupId@
  artifactId: @project.artifactId@
  version: @project.version@

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  config: classpath:log4j2.xml
eureka:
  instance:
    easeRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    prefer-ip-address: true
    metadata-map:
      user.name: admin
      user.password: 149360
      management:
        context-path: /${spring.application.name}
  #    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/${spring.application.name}/eureka/
