spring:
  application:
    name: eureka-center
server:
  port: 8761
  context-path: /${spring.application.name}
logging:
  config: classpath:log4j2.xml
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
security:
  user:
    name: admin
    password: 149360